### PR TITLE
Ship has a Storage

### PR DESCRIPTION
**Pull request by ewoudje**
To be used together with https://github.com/ValkyrienSkies/Valkyrien-Skies-2/pull/56 ; if api is good then i will make a good wrapping around it with ResourceLocation's

### CODE REVIEW

**Comment by Rubydesic** [comment]
Why is this in ShipDataCommon with PacketIgnore? If it's supposed to be server-side it should be in ShipData. Also I think we be a little more type-safe by using something like the guava ClassToInstanceMap so that you don't have to cast object every time.

**Comment by ewoudje** [comment]
Yhea indeed it should be more type safe, the location i wanted it to be client and server-sided since there might be data in there that you want to use for rendering; but im unsure if its correct to put it in ShipDataCommon

**Comment by ewoudje** [comment]
But a class to instance, i don't think thats good cus i want to store multiple things of the same type (integers strings etc).
An example of a usecase of this would be ship.getStorage("vs_eureka:max_speed") in the helm.

**Comment by ewoudje** [comment]
Closing new api ideas etc, so opening new branch with new PR

**Pull request closed without merging**
